version: '3'

services:
  usermanagement:
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    ports:
      - "8001:8080"
    environment:
      DataAccessSettings__ConnectionString: "Server=mssql;Database=master;User=sa;Password=Your_password123;Encrypt=False"
    depends_on:
      - mssql

  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"